spring:
  config:
    activate:
      on-profile: local-stack

server:
  port: 8080

dataimporter:
  spreadsheet-id: "1Ya7J-nsc2m4D9MuiDbauypL7yWocHGoJj9P7tVimxp8"
  sheet-range: "Telegram аккаунты студентов!A2:C"
  admin-ids: []
  auth-service-base-url: "http://auth-service:8080"

management:
    endpoint:
        health:
          show-details: always