spring:
  config:
    activate:
      on-profile: staging

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      security.protocol: ${KAFKA_SECURITY_PROTOCOL}
      sasl.mechanism: ${KAFKA_SASL_MECHANISM}
      sasl.jaas.config: ${KAFKA_SASL_JAAS_CONFIG}
      ssl.truststore.type: ${KAFKA_SSL_TRUSTSTORE_TYPE}
      ssl.truststore.location: ${KAFKA_SSL_TRUSTSTORE_LOCATION}
    topic:
      projects-project-created: staging.projects.project.created

server:
  port: 8080

dataimporter:
  project-spreadsheet-id: ${PROJECT_SPREADSHEET_ID}
  mentor-spreadsheet-id: ${MENTOR_SPREADSHEET_ID}
  guaranteed-reviews-spreadsheet-id: ${GUARANTEED_REVIEWS_SPREADSHEET_ID}
  auth-service-base-url: "http://auth-service:8080"
  profile-service-base-url: "http://profile-service:8080"
  project-service-base-url: "http://project-service:8080"
  mentor-service-base-url: "http://mentor-service:8080"
  interval-repetition-service-base-url: "http://interval-repetition-service:8080"
  interview-question-sources:
    - specialization: "Java Backend"
      spreadsheet-id: ${JAVA_SPREADSHEET_ID}
    - specialization: "Python Backend"
      spreadsheet-id: ${PYTHON_SPREADSHEET_ID}

management:
  endpoint:
    health:
      show-details: always