spring:
  config:
    activate:
      on-profile: staging

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      security.protocol: ${KAFKA_SECURITY_PROTOCOL}
      sasl.mechanism: ${KAFKA_SASL_MECHANISM}
      sasl.jaas.config: ${KAFKA_SASL_JAAS_CONFIG}
      ssl.truststore.type: ${KAFKA_SSL_TRUSTSTORE_TYPE}
      ssl.truststore.location: ${KAFKA_SSL_TRUSTSTORE_LOCATION}

server:
  port: 8080

dataimporter:
  project-spreadsheet-id: "1Ya7J-nsc2m4D9MuiDbauypL7yWocHGoJj9P7tVimxp8"
  mentor-spreadsheet-id: "1DkIIcE6oUtcK9jjfrOyUgatb6DIxL5GXEn3kvUp4Lms" # продовая таблца
  sheet-range-telegram-accounts: "Telegram аккаунты студентов!A2:C"
  sheet-range-projects: "Projects!A3:I"
  sheet-range-reviews: "B7:E"
  admin-ids: []
  auth-service-base-url: "http://auth-service:8080"
  profile-service-base-url: "http://profile-service:8080"
  project-service-base-url: "http://project-service:8080"
  mentor-service-base-url: "http://mentor-service:8085"

management:
  endpoint:
    health:
      show-details: always