spring:
  config:
    activate:
      on-profile: staging

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      security.protocol: ${KAFKA_SECURITY_PROTOCOL}
      sasl.mechanism: ${KAFKA_SASL_MECHANISM}
      sasl.jaas.config: ${KAFKA_SASL_JAAS_CONFIG}
      ssl.truststore.type: ${KAFKA_SSL_TRUSTSTORE_TYPE}
      ssl.truststore.location: ${KAFKA_SSL_TRUSTSTORE_LOCATION}
    topic:
      projects-project-created: staging.projects.project.created

server:
  port: 8080

dataimporter:
  project-spreadsheet-id: "1CLWecxLuA2x8y9zTpQ-NhI-vvS7jtI9eWLdXJBm1vXM"
  mentor-spreadsheet-id: "1ZhGCosIRZZHKK1bigXT0dX0P08CJwXWT-8gAtxbE49M"
  sheet-range-telegram-accounts: "Telegram аккаунты студентов!A2:C"
  sheet-range-projects: "Projects!A3:I"
  sheet-range-reviews: "B7:E"
  auth-service-base-url: "http://auth-service:8080"
  profile-service-base-url: "http://profile-service:8080"
  project-service-base-url: "http://project-service:8080"
  mentor-service-base-url: "http://mentor-service:8080"

management:
  endpoint:
    health:
      show-details: always