spring:
  application:
    name: data-importer
  config:
    import: optional:file:.env[.properties]

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: data-importer-cg
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.itmentorcommunityplatform.dataimporter.dto.event.ProjectCreatedEvent
        spring.json.use.type.headers: false
    listener:
      missing-topics-fatal: true

logging:
    level:
      root: INFO

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: "health,prometheus,info"
  endpoint:
    prometheus:
      access: unrestricted
    health:
      show-details: when_authorized

dataimporter:
  sheet-range-telegram-accounts: "Telegram аккаунты студентов!A2:C"
  sheet-range-projects: "Projects!A3:I"
  sheet-range-guaranteed-reviews: "B7:E"
  sheet-range-project-reviews: "Reviews!A2:I"
  sheet-range-mentors: "Менторы!A5:L"  

google:
  credentials:
    json: ${GOOGLE_APPLICATION_CREDENTIALS_JSON:}

