spring:
  application:
    name: data-importer

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: data-importer-cg
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.itmentorcommunityplatform.dataimporter.dto.event.ProjectCreatedEvent
        spring.json.use.type.headers: false
    listener:
      missing-topics-fatal: true

logging:
    level:
      root: INFO

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: "health,prometheus,info"
  endpoint:
    prometheus:
      access: unrestricted
    health:
      show-details: when_authorized

google:
  credentials:
    path: ${GOOGLE_APPLICATION_CREDENTIALS:}
    json: ${GOOGLE_APPLICATION_CREDENTIALS_JSON:}