name: Build and Push Docker Image

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch name
        id: branch
        run: |
          RAW_NAME=${GITHUB_REF_NAME}
          SAFE_NAME=$(echo "$RAW_NAME" | tr '/' '-' | tr -cd '[:alnum:]._-')
          echo "name=$SAFE_NAME" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/data-importer:${{ steps.branch.outputs.name }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/data-importer:${{ steps.branch.outputs.name }}